### ISSUE TITLE
sni.velox.ch does not exist anymore

### ISSUE THREAD

**Issue by eserte** [nalobin/AnyEvent-TLS-SNI#2]
The test suite fails since some months:
```
$ perl5.25.12 -Mblib t/01.t 
not ok 1 - SNI on
#   Failed test 'SNI on'
#   at t/01.t line 30.
1..1
# Looks like you failed 1 test of 1.
```
Probably it's failing because the host referenced in the script does not exist anymore:
```
$ host sni.velox.ch         
Host sni.velox.ch not found: 3(NXDOMAIN)
```

**Comment by nalobin** [comment]
Yes, site does not exist anymore... Do you know some alternative?

**Comment by eserte** [comment]
Sorry, don't know of any alternative, I just stumbled over the problem while smoking the CPAN...

**Comment by nalobin** [comment]
switched off this test in 0.04
